### ISSUE TITLE
Network configuration on SimuLink RealTime

### ISSUE THREAD

**Issue by AlexPapaver** [mathworks/ecal-toolbox#2]
Please help.
built eCALlibs for QNX on Windows, then copy it on target, configure network in cloud mode for host and set Multicast in eCalUtils for target.
But when I tried to launch tests, I can't recieve any data. I tried samples and simulink builds too.

That's what i have in console:

```
$ ./ecal_sample_person_snd
eCAL::Config - Could not load ini file, using defaults. File name : D:/ecal-toolbox/_install_qnx/etc/ecal/ecal.ini
CUDPReceiver: Unable to set receive buffer size: No buffer space available
CUDPReceiver: Unable to set receive buffer size: No buffer space available
person id    : 1
person name  : Max
person stype : 0
person email : max@mail.net
dog.name     : Brandy
house.rooms  : 4
```
As you can see, it compiled with wrong directory, but i can't understand how to change it

what can i do whit that? 
Thank you for help

**Comment by windelbouwman** [comment]
Setting up UDP multicast is a bit tricky. Here is a checklist:

- add multicast route on qnx: route add -net 239.0.0.0 -netmask 255.255.255.0 -iface 192.168.x.y -mtu 1000
- add multicast route on windows
- Enable "cloud" mode on windows side
- Check firewall settings on windows side
- Use ecal_sample_person_snd on QNX, and ecal_sample_person_rec on windows (as a test)
- Use ecal_monitor on windows

I got the same errors / warnings about the ecal.ini folder, but it worked in the end.
